# Exercise - Rollback AWSTemplateFormatVersion: 2010-09-09 
Description: ND9991 C3 L4
Resources:
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '192.168.0.0/24'
      Tags:
        - Key: Name
          Value: "udacity-vpc"
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '192.168.0.0/24'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'udacity-subnet1'
      VpcId: !Ref MainVPC
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: 'udacity-keypair'
      ImageId: 'ami-09cd747c78a9add63'
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Ref: "PublicSubnet1"

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
