version: 2.1

jobs:
#  create_infrastructure:
#    docker:
#      - image: amazon/aws-cli
#    steps:
#      - checkout
#      - run:
#          name: CreateCloudformation Stack
#          command: |
#            aws cloudformation deploy \
#              --template-file template.yml \
#              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#              --region us-east-1
  configure_infrastructure:
    docker:
     - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["e4:cc:9e:58:b1:5b:2d:1c:46:89:20:28:d0:4c:12:12"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: ssh key
          command: |
            ls -l ~/.ssh
            cat ~/.ssh/id_rsa.pub
      - run:
          name: Run playbook and configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  my-workflow:
    jobs:
#      - create_infrastructure
      - configure_infrastructure
